[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name="consoleplusplus"
version="0.1.0"
description="check README.md"
authors=["skiscratcher"]